# Generated by Django 4.2.2 on 2023-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.ImageField(upload_to='car_pics'),
        ),
    ]
