# Generated by Django 4.2.2 on 2023-06-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='album_name',
            field=models.CharField(error_messages={'unique': 'You dum dum. Your album name is too common!'}, max_length=30, unique=True),
        ),
    ]
